build:
 version: "11.2"

cards:
 message: "Welcome to cards related local apis"
 contactDetails:
   name: "Gurpreet Singh -Developer"
   email: "er.gurdevcards@yahoo.com"
 onCallSupport:
   - 123456789
   - 234567890