services:
 accountsdb:
  container_name: accountsdb
  ports:
   - 3306:3306
  environment:
   MYSQL_DATABASE: accountsdb
  extends:
   service: microservices-db-config
   file: common-config.yml

 loansdb:
  container_name: loansdb
  ports:
   - 3307:3306
  environment:
   MYSQL_DATABASE: loansdb
  extends:
   service: microservices-db-config
   file: common-config.yml

 cardsdb:
  container_name: cardsdb
  ports:
   - 3308:3306
  environment:
   MYSQL_DATABASE: cardsdb
  extends:
   service: microservices-db-config
   file: common-config.yml

 configserver:
  image: "gurpreet619/configserver:s7"
  container_name: configserver-ms
  ports:
   - "8071:8071"
  healthcheck:
   #test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP | exit 1"
   test: [ "CMD", "curl", "-f", "http://localhost:8071/actuator/health" ]
   interval: 30s
   timeout: 5s
   retries: 10
   start_period: 10s
  extends:
   file: common-config.yml
   service: microservice-base-config

 accounts:
  image: "gurpreet619/accounts:s7"
  container_name: accounts-ms
  ports:
   - "8080:8080"
  depends_on:
   configserver:
    condition: service_healthy
   accountsdb:
    condition: service_healthy
  environment:
    - SPRING_APPLICATION_NAME:"accounts"
    - SPRING_DATASOURCE_URL:"jdbc:mysql://accountsdb:3306/accountsdb"
  extends:
   file: common-config.yml
   service: microservice-configserver-config

 loans:
  image: "gurpreet619/loans:s7"
  container_name: loans-ms
  ports:
   - "8090:8090"
  depends_on:
   configserver:
    condition: service_healthy
   loansdb:
    condition: service_healthy
  environment:
   - SPRING_APPLICATION_NAME:"loans"
   - SPRING_DATASOURCE_URL:"jdbc:mysql://loansdb:3306/loansdb"
  extends:
   file: common-config.yml
   service: microservice-configserver-config

 cards:
  image: "gurpreet619/cards:s7"
  container_name: cards-ms
  ports:
   - "9000:9000"
  depends_on:
   configserver:
    condition: service_healthy
   cardsdb:
    condition: service_healthy
  environment:
   - SPRING_APPLICATION_NAME:"cards"
   - SPRING_DATASOURCE_URL:"jdbc:mysql://cardsdb:3306/cardsdb"
  extends:
   file: common-config.yml
   service: microservice-configserver-config

networks:
 bankapp:
  driver: "bridge"